name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential libgtk-3-dev sox
          version: 1.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel==0.38.1
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Run pytest
        run: pytest -vv test/
