# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.4
    - name: Install gtk-3-dev, build-essential and sox
      run: |
        sudo apt-get install build-essential libgtk-3-dev sox
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        python3 -m pytest -vv test/
